name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
           maven-version: 3.8.2
      - run: |
           mvn -v
           mvn compile
           mvn package


         
