name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: output readme
        id: cowsay_readme
        uses: Code-Hex/neo-cowsay-action@v1
        with:
         path: ./README.md
      - name: print output
        run: |
            echo "${{ steps.cowsay_readme.outputs.cowsay }}"