name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Read readme.md
        id: readme
        uses: juliangruber/read-file-action@v1
        with:
           path: ./README.md
      - name: output readme
        id: cowsay_readme
        uses: Code-Hex/neo-cowsay-action@v1
        with:
         message: ${{ steps.readme.outputs.content }}
